services:
  - type: web
    name: hepatox
    env: python
    buildCommand: pip install -r requirements.txt && python train_models.py
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
